name: Prueba

on: 
  push:
    paths:
      - 'action.yml'

  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    name: A job to run test
    steps:
    - name: Clone repository manually
      run: git clone https://github.com/MasterCloudApps/4.2.Integracion-y-entrega-continua-ejem-1 .
    - name: Checkout action
      uses: actions/checkout@v3
      with:
        path: ./action
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Run Maven Action
      id: maven-gha
      uses: ./action/
      with:
        package: false
        exclude: 'selenium'
    - name: Get project version
      run: |
        [[ ${{ steps.maven-gha.outputs.project-version }} == "0.0.1-SNAPSHOT" ]] && echo "Works" || ( echo "Fail" && exit 1 )
