name: Prueba

on: 
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    name: A job to run test
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        repository: 'MasterCloudApps/4.2.Integracion-y-entrega-continua-ejem-1'
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Run Maven Action
      id: maven-gha
      uses: ./ # Uses an action in the root directory
      with:
        package: false
        exclude: 'selenium'
    - name: Get project version
      run: |
        [[ ${{ steps.maven-gha.outputs.project-version }} == "0.1.0-SNAPSHOT" ]] && echo "Works" || ( echo "Fail" && exit 1 )
